name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: "What problem do you have today?"
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What action was you attempting to do?
      placeholder: What did you get?
      value: "Example: Stop a VM in the admin panel"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What platform are you using?
      multiple: false
      options:
        - Windows
        - Linux
        - macOS
        - None of the above
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: thread apply all bt
      description: Paste unbroken gdb output here. (REBUILD AS DEBUG FIRST)
      render: shell