name: CollabVM Server

on: [push, pull_request]

jobs:
  windows_x64_msys2: # Windows Server 2019 (x64)
    runs-on: windows-2019
    strategy:
      matrix:
        set: [{"base": "ucrt", "compiler": "clang", "xxcompiler": "clang++"},{"base": "clang", "compiler": "clang", "xxcompiler": "clang++"}]
    steps:
      - uses: actions/checkout@main
      - name: Install ${{matrix.set.base}}64 Env and Dependencies
        id: depends
        shell: C:\\msys64\\usr\\bin\\env.exe -i /usr/bin/bash --noprofile --norc -e -o pipefail {0}
        run: | 
          pacman -S mingw-w64-${{matrix.set.base}}-x86_64-make mingw-w64-${{matrix.set.base}}-x86_64-${{matrix.set.compiler}} mingw-w64-${{matrix.set.base}}-x86_64-libvncserver mingw-w64-${{matrix.set.base}}-x86_64-cairo mingw-w64-${{matrix.set.base}}-x86_64-dlfcn mingw-w64-${{matrix.set.base}}-x86_64-boost mingw-w64-${{matrix.set.base}}-x86_64-sqlite3 mingw-w64-${{matrix.set.base}}-x86_64-winpthreads-git --noconfirm
      - name: Build server
        id: build
        shell: C:\\msys64\\usr\\bin\\env.exe -i /usr/bin/bash --noprofile --norc -e -o pipefail {0}
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: |
          PATH=/c/msys64/${{matrix.set.base}}64/bin:/c/msys64/mingw64/bin:$PATH
          export CC=/c/msys64/${{matrix.set.base}}64/bin/${{matrix.set.compiler}}
          export CXX=/c/msys64/${{matrix.set.base}}64/bin/${{matrix.set.xxcompiler}}
          mingw32-make JPEG=1